version: '3'
services:

  app:
    build: .
    restart: unless-stopped
    environment:
      - APP_NAME=FlaskApp
      - FLASK_APP=server:app
    ports:
      - 5000:8080
    links:
      - redis
    volumes:
      - ./app:/app

  redis:
    image: redis:latest
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
    expose:
      - 6379